version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks:
  ApplicationStop:
    - location: scripts/stop_docker.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/pull_docker.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root